# EDA & Feature Engineering

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("Customer_Churn_Dataset.csv")
df

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No
7040,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes
7042,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

In [4]:
df.describe()

       SeniorCitizen       tenure  MonthlyCharges
count    7043.000000  7043.000000     7043.000000
mean        0.162147    32.371149       64.761692
std         0.368612    24.559481       30.090047
min         0.000000     0.000000       18.250000
25%         0.000000     9.000000       35.500000
50%         0.000000    29.000000       70.350000
75%         0.000000    55.000000       89.850000
max         1.000000    72.000000      118.750000

In [5]:
print(df.head() , "\n" , df.sample(2) , "\n" , df.tail())

   customerID  gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0  7590-VHVEG  Female              0     Yes         No       1           No
1  5575-GNVDE    Male              0      No         No      34          Yes
2  3668-QPYBK    Male              0      No         No       2          Yes
3  7795-CFOCW    Male              0      No         No      45           No
4  9237-HQITU  Female              0      No         No       2          Yes

      MultipleLines InternetService OnlineSecurity  ... DeviceProtection  \
0  No phone service             DSL             No  ...               No
1                No             DSL            Yes  ...              Yes
2                No             DSL            Yes  ...               No
3  No phone service             DSL            Yes  ...              Yes
4                No     Fiber optic             No  ...               No

  TechSupport StreamingTV StreamingMovies        Contract PaperlessBilling  \
0          No          No              No  Month-to-month              Yes
1          No          No              No        One year               No
2          No          No              No  Month-to-month              Yes
3         Yes          No              No        One year               No
4          No          No              No  Month-to-month              Yes

               PaymentMethod MonthlyCharges  TotalCharges Churn
0           Electronic check          29.85         29.85    No
1               Mailed check          56.95        1889.5    No
2               Mailed check          53.85        108.15   Yes
3  Bank transfer (automatic)          42.30       1840.75    No
4           Electronic check          70.70        151.65   Yes

[5 rows x 21 columns]
       customerID gender  SeniorCitizen Partner Dependents  tenure  \
3707  9537-JALFH   Male              0     Yes        Yes      69
1320  8947-YRTDV   Male              0     Yes        Yes      32

     PhoneService MultipleLines InternetService       OnlineSecurity  ...  \
3707          Yes            No              No  No internet service  ...
1320          Yes            No     Fiber optic                  Yes  ...

         DeviceProtection          TechSupport          StreamingTV  \
3707  No internet service  No internet service  No internet service
1320                  Yes                   No                   No

          StreamingMovies  Contract PaperlessBilling  \
3707  No internet service  Two year               No
1320                  Yes  One year               No

                  PaymentMethod MonthlyCharges  TotalCharges Churn
3707  Bank transfer (automatic)           19.9        1356.7    No
1320               Mailed check           94.8       3131.55    No

[2 rows x 21 columns]
       customerID  gender  SeniorCitizen Partner Dependents  tenure  \
7038  6840-RESVB    Male              0     Yes        Yes      24
7039  2234-XADUH  Female              0     Yes        Yes      72
7040  4801-JZAZL  Female              0     Yes        Yes      11
7041  8361-LTMKD    Male              1     Yes         No       4
7042  3186-AJIEK    Male              0      No         No      66

     PhoneService     MultipleLines InternetService OnlineSecurity  ...  \
7038          Yes               Yes             DSL            Yes  ...
7039          Yes               Yes     Fiber optic             No  ...
7040           No  No phone service             DSL            Yes  ...
7041          Yes               Yes     Fiber optic             No  ...
7042          Yes                No     Fiber optic            Yes  ...

     DeviceProtection TechSupport StreamingTV StreamingMovies        Contract  \
7038              Yes         Yes         Yes             Yes        One year
7039              Yes          No         Yes             Yes        One year
7040               No          No          No              No  Month-to-month
7041               No          No          No              No  Month-to-month
7042              Yes         Yes         Yes             Yes        Two year

     PaperlessBilling              PaymentMethod MonthlyCharges  TotalCharges  \
7038              Yes               Mailed check          84.80        1990.5
7039              Yes    Credit card (automatic)         103.20        7362.9
7040              Yes           Electronic check          29.60        346.45
7041              Yes               Mailed check          74.40         306.6
7042              Yes  Bank transfer (automatic)         105.65        6844.5

     Churn
7038    No
7039    No
7040    No
7041   Yes
7042    No

[5 rows x 21 columns]

In [6]:
df.columns

Index(['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'tenure', 'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='object')

#### Feature Engineering

In [7]:
# Selecting only useful features for Model training
df1 = df[['tenure','MonthlyCharges','Churn']].copy()
df1

      tenure  MonthlyCharges Churn
0          1           29.85    No
1         34           56.95    No
2          2           53.85   Yes
3         45           42.30    No
4          2           70.70   Yes
...      ...             ...   ...
7038      24           84.80    No
7039      72          103.20    No
7040      11           29.60    No
7041       4           74.40   Yes
7042      66          105.65    No

[7043 rows x 3 columns]

In [8]:
df1.rename(columns={'MonthlyCharges': 'monthly_charges'}, inplace=True)
df1

      tenure  monthly_charges Churn
0          1            29.85    No
1         34            56.95    No
2          2            53.85   Yes
3         45            42.30    No
4          2            70.70   Yes
...      ...              ...   ...
7038      24            84.80    No
7039      72           103.20    No
7040      11            29.60    No
7041       4            74.40   Yes
7042      66           105.65    No

[7043 rows x 3 columns]

In [9]:
#Creating complaints,age and feature
df1['complaints'] = (df1['monthly_charges'] > 70).astype(int)
df1['age'] = 25 + (df1['tenure'] % 30)
df1['last_login_days'] = df1['tenure'] % 20
df1

      tenure  monthly_charges Churn  complaints  age  last_login_days
0          1            29.85    No           0   26                1
1         34            56.95    No           0   29               14
2          2            53.85   Yes           0   27                2
3         45            42.30    No           0   40                5
4          2            70.70   Yes           1   27                2
...      ...              ...   ...         ...  ...              ...
7038      24            84.80    No           1   49                4
7039      72           103.20    No           1   37               12
7040      11            29.60    No           0   36               11
7041       4            74.40   Yes           1   29                4
7042      66           105.65    No           1   31                6

[7043 rows x 6 columns]

In [10]:
df1["Churn"].unique()

array(['No', 'Yes'], dtype=object)

In [11]:
# Encoding Categorical data

# Mapping Churn
mapping = {
    'Yes' : 1,
    'No' : 0
}

df1["Churn"] = df1["Churn"].map(mapping)
df1 = df1[["age","tenure","monthly_charges","last_login_days","complaints","Churn"]]
df1

      age  tenure  monthly_charges  last_login_days  complaints  Churn
0      26       1            29.85                1           0      0
1      29      34            56.95               14           0      0
2      27       2            53.85                2           0      1
3      40      45            42.30                5           0      0
4      27       2            70.70                2           1      1
...   ...     ...              ...              ...         ...    ...
7038   49      24            84.80                4           1      0
7039   37      72           103.20               12           1      0
7040   36      11            29.60               11           0      0
7041   29       4            74.40                4           1      1
7042   31      66           105.65                6           1      0

[7043 rows x 6 columns]

In [12]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   age              7043 non-null   int64
 1   tenure           7043 non-null   int64
 2   monthly_charges  7043 non-null   float64
 3   last_login_days  7043 non-null   int64
 4   complaints       7043 non-null   int64
 5   Churn            7043 non-null   int64
dtypes: float64(1), int64(5)
memory usage: 330.3 KB

In [13]:
df1.dropna()
df1

      age  tenure  monthly_charges  last_login_days  complaints  Churn
0      26       1            29.85                1           0      0
1      29      34            56.95               14           0      0
2      27       2            53.85                2           0      1
3      40      45            42.30                5           0      0
4      27       2            70.70                2           1      1
...   ...     ...              ...              ...         ...    ...
7038   49      24            84.80                4           1      0
7039   37      72           103.20               12           1      0
7040   36      11            29.60               11           0      0
7041   29       4            74.40                4           1      1
7042   31      66           105.65                6           1      0

[7043 rows x 6 columns]

In [14]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   age              7043 non-null   int64
 1   tenure           7043 non-null   int64
 2   monthly_charges  7043 non-null   float64
 3   last_login_days  7043 non-null   int64
 4   complaints       7043 non-null   int64
 5   Churn            7043 non-null   int64
dtypes: float64(1), int64(5)
memory usage: 330.3 KB

In [16]:
final_data = df1
df1

      age  tenure  monthly_charges  last_login_days  complaints  Churn
0      26       1            29.85                1           0      0
1      29      34            56.95               14           0      0
2      27       2            53.85                2           0      1
3      40      45            42.30                5           0      0
4      27       2            70.70                2           1      1
...   ...     ...              ...              ...         ...    ...
7038   49      24            84.80                4           1      0
7039   37      72           103.20               12           1      0
7040   36      11            29.60               11           0      0
7041   29       4            74.40                4           1      1
7042   31      66           105.65                6           1      0

[7043 rows x 6 columns]

# ML Model Training and Testing

In [18]:
X = final_data[["age", "tenure", "monthly_charges", "last_login_days", "complaints"]]  #Independent Features
y = final_data["Churn"] #Target Features

In [19]:
# Train-Test Split (80-20)
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [20]:
#Train Model

from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(random_state=42)
model.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [21]:
# Checking Accuracy
from sklearn.metrics import accuracy_score

y_pred = model.predict(X_test)

acc = accuracy_score(y_test, y_pred)
print("Accuracy:", acc)

Accuracy: 0.7395315826827538

In [22]:
# Save model
import joblib

joblib.dump(model, "churn_model.pkl")

['churn_model.pkl']

In [25]:
# Test
sample = pd.DataFrame({
    "age": [35],
    "tenure": [12],
    "monthly_charges": [85],
    "last_login_days": [5],
    "complaints": [1]
})

print(model.predict(sample))
print(model.predict(sample)[0])

[1]
1

In [26]:
model.predict_proba(sample)
model.predict_proba(sample)[0][1]

np.float64(0.6714999999999999)